language: java
sudo: false
jdk:
  - openjdk8
install: true
script:
  ./gradlew check
cache:
  directories:
  - $HOME/.gradle/caches/
  - $HOME/.gradle/wrapper/
# safelist
branches:
  only:
  - master
notifications:
  email: false