language: java
sudo: false
jdk:
  - openjdk8
install: true
script:
  ./gradlew test
cache:
  directories:
  - $HOME/.gradle/caches/
  - $HOME/.gradle/wrapper/
# safelist
branches:
  only:
  - develop
  - master
  - /^feature_.*$/
notifications:
  email: false