version: "{branch} {build}"

build:
  verbosity: detailed

build_script:
  - gradlew.bat --info assemble

test_script:
  - gradlew.bat --info check

branches:
  only:
  - develop
  - master
  - /^feature_.*$/

environment:
  matrix:
  - JAVA_HOME: C:\Program Files\Java\jdk1.8.0
  - JAVA_HOME: C:\Program Files (x86)\Java\jdk1.8.0

cache:
  - C:\Users\appveyor\.gradle