version: "{branch} {build}"

build:
  verbosity: detailed

build_script:
  - gradlew.bat --no-daemon assemble

test_script:
  - gradlew.bat --no-daemon check

branches:
  only:
  - master

environment:
  matrix:
  - JAVA_HOME: C:\Program Files\Java\jdk1.8.0
  - JAVA_HOME: C:\Program Files (x86)\Java\jdk1.8.0
  - JAVA_HOME: C:\Program Files\Java\jdk11

cache:
  - C:\Users\appveyor\.gradle